### ISSUE TITLE
globus-connect-server-setup public_name() and public_ip() returning wrong values on specific non-ec2 system

### ISSUE THREAD

**Issue by danpowers** [globus/globus-connect-server#21]
see https://globusonline.zendesk.com/agent/tickets/345764

globus-connect-server-setup [public_name()](https://github.com/globus/globus-connect-server/blob/master/source/globus/connect/server/__init__.py#L88) and [public_ip()](https://github.com/globus/globus-connect-server/blob/master/source/globus/connect/server/__init__.py#L109) returning wrong values on specific non-ec2 system.

Admin's system is CentOS7 system not running on an ec2 instance. From the admin's system, a host 169.254.169.254 is reachable with a web server listening on port 80, and it returns 404s formatted like so:
```
# curl -v http://169.254.169.254/latest/meta-data/public-hostname
* About to connect() to 169.254.169.254 port 80 (#0)
* Trying 169.254.169.254...
* Connected to 169.254.169.254 (169.254.169.254) port 80 (#0)
> GET /latest/meta-data/public-hostname HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 169.254.169.254
> Accept: */*
>
< HTTP/1.1 404 Not Found
< Content-Length: 154
< Content-Type: text/html; charset=UTF-8
< Date: Thu, 02 May 2019 15:33:30 GMT
<
<html>
<head>
<title>404 Not Found</title>
</head>
<body>
<h1>404 Not Found</h1>
The resource could not be found.<br /><br />

</body>
* Connection #0 to host 169.254.169.254 left intact
</html>
```
The [public_name()](https://github.com/globus/globus-connect-server/blob/master/source/globus/connect/server/__init__.py#L88) and [public_ip()](https://github.com/globus/globus-connect-server/blob/master/source/globus/connect/server/__init__.py#L109) functions don't catch these 404 messages, causing the message contents to be dumped inappropriately into data_interface and [defaults["HOSTNAME"].](https://github.com/globus/globus-connect-server/blob/master/source/globus/connect/server/configfile.py#L357)

The message gets dumped into [data_interface](https://github.com/globus/globus-connect-server/blob/master/source/globus/connect/server/io/__init__.py#L197) if [GridFTP].DataInterface is not set in the gcs.conf file, causing it to show in the data_interface value in the /etc/gridftp.d/globus-connect-server file.

If "Server = %(HOSTNAME)s" is set, the message gets dumped into the server value for the service causing gcs-setup to fail like so:

> Invalid value for Server in [GridFTP] section of /etc/globus-connect-server.conf: 404 Not Found

It was possible to work around the issue by having the admin set [GridFTP].DataInterface, [GridFTP].Server, and [MyProxy].Server to the appropriate FQDN hostname.

**Comment by bester** [comment]
Fixed in 4.0.56
